//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LordMarket.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LordMarketDBEntities : DbContext
    {
        public LordMarketDBEntities()
            : base("name=LordMarketDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GelirGider> GelirGider { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilar { get; set; }
        public virtual DbSet<Musteriler> Musteriler { get; set; }
        public virtual DbSet<SatisIslem> SatisIslem { get; set; }
        public virtual DbSet<Urunler> Urunler { get; set; }
    
        public virtual int SatisYap(string odemeTipi, Nullable<System.DateTime> tarih)
        {
            var odemeTipiParameter = odemeTipi != null ?
                new ObjectParameter("OdemeTipi", odemeTipi) :
                new ObjectParameter("OdemeTipi", typeof(string));
    
            var tarihParameter = tarih.HasValue ?
                new ObjectParameter("Tarih", tarih) :
                new ObjectParameter("Tarih", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SatisYap", odemeTipiParameter, tarihParameter);
        }
    
        public virtual int sp_GuncelleSatisNo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GuncelleSatisNo");
        }
    
        public virtual int UpdateNullToplamTutar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateNullToplamTutar");
        }
    
        public virtual int UpdateToplamTutarFromUrunListesi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateToplamTutarFromUrunListesi");
        }
    }
}
