//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LordMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteriler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Musteriler()
        {
            this.SatisIslem = new HashSet<SatisIslem>();
        }
    
        public int ID { get; set; }
        public string MusteriAdSoyad { get; set; }
        public string Notlar { get; set; }
        public Nullable<decimal> ToplamBorc { get; set; }
        public Nullable<System.DateTime> SonGuncellenmeTarihi { get; set; }
        public string BosAlan { get; set; }
        public Nullable<bool> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SatisIslem> SatisIslem { get; set; }
    }
}
