//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LordMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteriler
    {
        public int ID { get; set; }
        public string MusteriAdSoyad { get; set; }
        public Nullable<int> SatisIslemID { get; set; }
        public string Notlar { get; set; }
        public Nullable<decimal> ToplamBorc { get; set; }
        public string SonGuncellenmeTarihi { get; set; }
        public string BosAlan { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual SatisIslem SatisIslem { get; set; }
    }
}
