//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LordMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satislar
    {
        public int ID { get; set; }
        public Nullable<int> UrunID { get; set; }
        public Nullable<int> SatisIslemID { get; set; }
        public Nullable<decimal> Tutar { get; set; }
        public string SatisTarihi { get; set; }
        public string BosAlan { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual SatisIslem SatisIslem { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
