//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LordMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SatisIslem
    {
        public int ID { get; set; }
        public Nullable<int> SatisNo { get; set; }
        public Nullable<decimal> ToplamTutar { get; set; }
        public string OdemeTipi { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string UrunListesi { get; set; }
        public Nullable<int> MusteriID { get; set; }
        public string BosAlan { get; set; }
        public Nullable<bool> Status { get; set; }
        public string IslemYapanKullanici { get; set; }
    
        public virtual Musteriler Musteriler { get; set; }
    }
}
