//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LordMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SatisIslem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SatisIslem()
        {
            this.Musteriler = new HashSet<Musteriler>();
            this.Satislar = new HashSet<Satislar>();
        }
    
        public int ID { get; set; }
        public string SatisNo { get; set; }
        public Nullable<decimal> ToplamTutar { get; set; }
        public string OdemeTipi { get; set; }
        public string Tarih { get; set; }
        public string BosAlan { get; set; }
        public Nullable<bool> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Musteriler> Musteriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Satislar> Satislar { get; set; }
    }
}
