//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LordMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToptanciIslem
    {
        public int ID { get; set; }
        public Nullable<int> ToptanciID { get; set; }
        public Nullable<decimal> AlacakToplam { get; set; }
        public Nullable<decimal> VerecekToplam { get; set; }
        public Nullable<System.DateTime> SonGuncellemeTarihi { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
